name: e_bill
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: any # Add version if needed
  google_fonts: any
  android_path_provider: any
  permission_handler: any
  url_launcher: any
  provider: any
  share_whatsapp: any
  shared_preferences: any
  image_gallery_saver: any
  http: any
  drop_down_search_field: any
  dropdownfield2: ^1.0.7
  path_provider: any
  shimmer:
  intl: ^0.18.0 # Ensure a valid version of the intl package
  dropdown_search:
  lottie:
  icons_launcher:
  animated_splash_screen:
  flutter_zoom_drawer:
dev_dependencies:
  flutter_test:
    sdk: flutter
icons_launcher:
  image_path: 'assets/icon/icon.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/icon/icon.png'
      notification_image: "assets/icon/icon.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: 'assets/icon/icon.png'
      adaptive_foreground_image: 'assets/icon/icon.png'
      adaptive_round_image: 'assets/icon/icon.png'
      adaptive_monochrome_image: 'assets/icon/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos.png
    - assets/images/bike.png
    - assets/images/car.png
    - assets/icon/Animation - 1729668326988.json


